@VkBot_HostAddress = http://localhost:5136

GET {{VkBot_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{VkBot_HostAddress}}/api/values

###

GET {{VkBot_HostAddress}}/api/values

###

@id=0
DELETE {{VkBot_HostAddress}}/api/values/{{id}}

###

POST {{VkBot_HostAddress}}/api/messageEndPoint/callback
Content-Type: application/json

{
  //JsonElement
}

###
POST {{VkBot_HostAddress}}/api/messageEndPoint/callback
Content-Type: application/json

{
  //JsonElement
}

###
